#
logging:
  file:
    path: log/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-30.30C{1.} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-30.30C{1.} : %m%n"
  level:
    com.pplove.hzwebapi: debug # 增加数据库查询打印


#
#
mybatis:
  #实体类所做包
  type-aliases-package: controller
  #mapper.xml所在位置
  mapper-locations:  classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanzhi?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  swagger2:
    enabled: true
pplove:
  msg: getchar
#mybatis-plus: #打印太多
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 10000
